# Genesis Settings
GENESIS_TIME: 1763757542

# Key Settings
ACTIVE_EPOCH: 18

# Validator Settings  
VALIDATOR_COUNT: 3

GENESIS_VALIDATORS:
    - "0ce82f1a75d83678462f4820f293ad3d80df1d5ba5546d6ecb0d5066c161bf72a28d93524f6c10343d6e67147e179d70d63a8978"
    - "80a3a23f78d6e11665b95d3ee8b61f4607477a734d245d7a002b56068ae7a43a3f7c6e4da08289628b5d7668e8650259cdecde5c"
    - "51028353acdcad69867b6336f1e61e7a059757181d1cbe1ed6a62a2e5ed84e0a8ccd682a5a7c7d573723fd12a76e2d3c80bd0d55"
