# Genesis Settings
GENESIS_TIME: 1764721502
# Key Settings
ACTIVE_EPOCH: 18
# Validator Settings
VALIDATOR_COUNT: 4
GENESIS_VALIDATORS:
  - "1290e5601c99833c608e02156ad9947eec4e0250f964520322b430470c0f1a3562dfc022e5dd690a7006750c682cc9339158110b"
  - "380c1975dfdb950a76aa1c358f5f980590839d2f2e27a070c4181538ca852c779315095ec85f4a0b898853433523382450982266"
  - "3bf52c5ba45b2c5ebae4eb6fb6f8b24d5377674d658ef13f18ad665a16ead04ba831c0728d113a3002ee8f5017959a5f0872e81b"
  - "af606e3c8ef8a425271a104853269d5038ae2c25cfa2e10fd6e71a3f4411d53e4d0784703a0ece2d38a81a715a8a9015fbec8437"
